(function(w,d){'use strict';
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  var style=d.createElement('style');style.id='ces-latest-fixes';style.textContent=`
    .swal2-actions{gap:10px!important;flex-wrap:wrap!important}.swal2-confirm,.swal2-cancel{min-width:112px!important;min-height:42px!important;padding:9px 16px!important;color:#fff!important;white-space:normal!important;line-height:1.25!important;overflow:visible!important}.swal2-confirm{background:#0756b8!important}.swal2-cancel{background:#dc2626!important}.swal2-popup{max-width:calc(100vw - 24px)!important}.swal2-html-container{overflow-wrap:anywhere!important}
    #view-inventory .csv5-actions,#view-inventory .sp-acc-actions,#view-check_stock .stockpro-actions{display:flex!important;gap:7px!important;flex-wrap:wrap!important;overflow:visible!important}#view-inventory .csv5-action,#view-inventory .sp-mini-btn{opacity:1!important;visibility:visible!important;min-width:36px!important;color:#fff!important}#view-inventory .csv5-action:not(.green):not(.orange):not(.red):not(.purple):not(.gray),#view-inventory .sp-mini-btn.blue{background:#0756b8!important}.csv5-action.green,.sp-mini-btn.green{background:#059669!important}.csv5-action.orange,.sp-mini-btn.orange{background:#d97706!important}.csv5-action.red,.sp-mini-btn.red{background:#dc2626!important}.csv5-action.purple{background:#7c3aed!important}.csv5-action.gray{background:#64748b!important}
    .swal2-popup .sc-popup-actions{display:grid!important;grid-template-columns:repeat(3,minmax(145px,1fr))!important;gap:9px!important;margin-top:16px!important}.swal2-popup .sc-popup-actions .sp-btn,.swal2-popup .sc-popup-actions .sc-white-action{display:inline-flex!important;align-items:center!important;justify-content:center!important;gap:7px!important;min-height:42px!important;border:0!important;border-radius:12px!important;padding:9px 12px!important;color:#fff!important;font-size:11px!important;font-weight:900!important;box-shadow:0 5px 13px rgba(15,23,42,.12)!important}.swal2-popup .sc-popup-actions .primary,.swal2-popup .sc-popup-actions .blue{background:#0756b8!important}.swal2-popup .sc-popup-actions .success,.swal2-popup .sc-popup-actions .green{background:#059669!important}.swal2-popup .sc-popup-actions .danger,.swal2-popup .sc-popup-actions .red{background:#dc2626!important}.swal2-popup .sc-popup-actions .ghost{background:#64748b!important}.swal2-popup .sc-popup-actions .soft{background:#7c3aed!important}.swal2-popup .sc-popup-actions .orange{background:#d97706!important}@media(max-width:640px){.swal2-popup .sc-popup-actions{grid-template-columns:1fr!important}}
    #view-inventory .acc-mini{color:#fff!important;border:0!important;box-shadow:0 4px 10px rgba(15,23,42,.1)!important}#view-inventory .acc-mini:not(.green):not(.orange):not(.blue):not(.red):not(.info){background:#e8eef7!important;color:#334155!important;border:1px solid #cbd5e1!important}#view-inventory .acc-mini.green{background:#059669!important}#view-inventory .acc-mini.orange{background:#d97706!important}#view-inventory .acc-mini.blue{background:#0756b8!important}#view-inventory .acc-mini.red{background:#dc2626!important}#view-inventory .acc-mini.info{background:#64748b!important;color:#fff!important}
    #view-audit_log .audit-type-icon,#view-audit_log .audit-progress-badge{display:none!important}#view-audit_log .audit-type-word{font-weight:950}.audit-type-word.finding-car{color:#dc2626}.audit-type-word.finding-obs{color:#ea580c}.audit-type-word.finding-suggestion{color:#2563eb}.audit-type-word.finding-other{color:#475569}.audit-framed{display:inline-flex;padding:4px 8px;border:1px solid;border-radius:999px;font-weight:800;line-height:1.3}.audit-framed.responsible{border-color:#93c5fd;background:#eff6ff;color:#1d4ed8}.audit-framed.root{border-color:#c4b5fd;background:#f5f3ff;color:#6d28d9}.audit-week-summary{display:grid;grid-template-columns:repeat(5,minmax(110px,1fr));gap:9px;padding:12px;background:#f8fbff;border-bottom:1px solid #dbe5ef;overflow:auto}.audit-week-summary>div{position:relative;overflow:hidden;border:1px solid #dbe5ef;border-radius:12px;background:#fff;padding:10px}.audit-week-summary small{display:block;color:#64748b;font-weight:800}.audit-week-summary b{display:block;margin-top:4px;color:#0756b8;font-size:18px}.audit-week-summary span{position:absolute;bottom:0;left:0;height:4px;background:#2563eb;border-radius:0 99px 99px 0}
    .ces-rental-workflow-summary-v248{display:flex!important;gap:8px!important;flex-wrap:wrap!important}.ces-rental-workflow-summary-v248>*{border-radius:12px!important;padding:8px 11px!important;background:#eff6ff!important;color:#0756b8!important;font-weight:900!important}
    #nc-log table{width:100%;border-collapse:collapse;min-width:850px;font-size:10px}#nc-log th{position:sticky;top:0;background:#eff6ff;color:#334155;text-align:left;padding:9px}#nc-log td{padding:8px 9px;border-bottom:1px solid #e5edf5;vertical-align:top}#nc-log .sent{color:#047857;font-weight:900}#nc-log .error{color:#dc2626;font-weight:900}#nc-log .skipped{color:#b45309;font-weight:900}
    .ces-checkout-complete{display:grid;grid-template-columns:1fr 1fr;gap:9px;text-align:left}.ces-checkout-complete label{font-size:10px;font-weight:850;color:#475569}.ces-checkout-complete .swal2-input,.ces-checkout-complete .swal2-select{margin:5px 0 0!important;width:100%!important;height:42px!important;font-size:12px!important}.ces-checkout-complete .wide{grid-column:1/-1}@media(max-width:620px){.ces-checkout-complete{grid-template-columns:1fr}.ces-checkout-complete .wide{grid-column:auto}.audit-week-summary{grid-template-columns:repeat(5,130px)}}`;
  d.head.appendChild(style);

  function patchSwal(){if(!w.Swal||w.Swal.__cesLatest)return;var base=w.Swal.fire.bind(w.Swal);w.Swal.fire=function(){var args=Array.prototype.slice.call(arguments);if(args[0]&&typeof args[0]==='object'){args[0]=Object.assign({},args[0]);if(args[0].showCancelButton){args[0].reverseButtons=true;args[0].cancelButtonText=args[0].cancelButtonText||'ยกเลิก';args[0].confirmButtonText=args[0].confirmButtonText||'ยืนยัน';args[0].confirmButtonColor='#0756b8';args[0].cancelButtonColor='#dc2626';}}return base.apply(null,args);};w.Swal.__cesLatest=true;}
  patchSwal();setTimeout(patchSwal,1000);

  function api(fn,args){return w.CES_API.callFunction(fn,args||[],{transport:'iframe',timeoutMs:120000,dedupe:false,priority:'active',userAction:true});}
  function stockPayload(){
    try{if(typeof SD_DASH!=='undefined'&&SD_DASH.raw&&Array.isArray(SD_DASH.raw.devices))return SD_DASH.raw;}catch(ignore){}
    try{if(typeof SI!=='undefined'&&SI.raw&&Array.isArray(SI.raw.devices))return SI.raw;}catch(ignore2){}
    try{var box=JSON.parse(localStorage.getItem('CES_STOCK_SNAPSHOT_STABLE')||'null');if(box&&box.data)return box.data;}catch(ignore3){}
    return null;
  }
  function exportRows(rows,fileName,sheetName){
    if(!w.XLSX)throw new Error('XLSX library is unavailable.');
    rows=Array.isArray(rows)?rows:[];if(!rows.length)throw new Error('No data available. Open the module once and try Export again.');
    var ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,String(sheetName||'Data').slice(0,31));
    XLSX.writeFile(wb,fileName+'_'+new Date().toISOString().slice(0,10)+'.xlsx');return{success:true,count:rows.length};
  }
  function appendExactSheet(wb,sheet){var aoa=[sheet.headers||[]].concat(sheet.rows||[]),ws=XLSX.utils.aoa_to_sheet(aoa);XLSX.utils.book_append_sheet(wb,ws,String(sheet.sheetName||'Data').slice(0,31));}
  function exportExactApi(fn,args,fileName){
    if(!w.XLSX)return Promise.reject(new Error('XLSX library is unavailable.'));
    if(w.Swal)Swal.fire({title:'Preparing XLSX…',allowOutsideClick:false,showConfirmButton:false,didOpen:function(){Swal.showLoading();}});
    return api(fn,args).then(function(res){if(!res||res.success===false)throw new Error(res&&res.message||'Export source is unavailable.');var wb=XLSX.utils.book_new(),sheets=Array.isArray(res.sheets)?res.sheets:[res];sheets.forEach(function(s){appendExactSheet(wb,s);});XLSX.writeFile(wb,fileName+'_'+new Date().toISOString().slice(0,10)+'.xlsx');if(w.Swal)Swal.close();return{success:true,sheets:sheets.length};}).catch(function(e){if(w.Swal)Swal.fire('Export Error',e.message||String(e),'error');throw e;});
  }
  async function exportChunkedSheets(specs,fileName){
    if(!w.XLSX)throw new Error('XLSX library is unavailable.');
    specs=Array.isArray(specs)?specs:[];if(!specs.length)throw new Error('No export sheets were selected.');
    if(w.Swal)Swal.fire({title:'Preparing XLSX…',html:'กำลังอ่านข้อมูลจากต้นฉบับแบบแบ่งชุด<br><b id="cesExportProgress">0%</b>',allowOutsideClick:false,showConfirmButton:false,didOpen:function(){Swal.showLoading();}});
    try{
      var wb=XLSX.utils.book_new();
      for(var s=0;s<specs.length;s++){
        var spec=specs[s],offset=0,headers=[],rows=[],sheetName=spec.name||'Data',done=false;
        while(!done){
          var res=await api('ces_getStockSheetExportChunkV3035',[{sheetKey:spec.key,offset:offset,limit:125}]);
          if(!res||res.success===false)throw new Error(res&&res.message||('Cannot export '+sheetName));
          if(!headers.length)headers=res.headers||[];Array.prototype.push.apply(rows,res.rows||[]);sheetName=res.sheetName||sheetName;
          done=res.done===true||res.nextOffset==null;offset=done?rows.length:Number(res.nextOffset||rows.length);
          var total=Math.max(1,Number(res.totalRows||rows.length)),part=Math.min(1,rows.length/total),pct=Math.round(((s+part)/specs.length)*100),progress=d.getElementById('cesExportProgress');if(progress)progress.textContent=pct+'% · '+sheetName+' '+rows.length.toLocaleString()+'/'+Number(res.totalRows||rows.length).toLocaleString();
        }
        appendExactSheet(wb,{sheetName:sheetName,headers:headers,rows:rows});
      }
      XLSX.writeFile(wb,fileName+'_'+new Date().toISOString().slice(0,10)+'.xlsx');if(w.Swal)Swal.close();return{success:true,sheets:specs.length};
    }catch(e){if(w.Swal)Swal.fire('Export Error',e.message||String(e),'error');throw e;}
  }
  function equipmentRows(){var p=stockPayload()||{},rows=p.devices||p.inventory||[];return rows.map(function(x){return{
    id_code:x.idCode||x.id_code||'',serial_number:x.sn||x.serialNumber||x.serial_number||'','Equipment Status':x.status||x.equipmentStatus||'',brand:x.brand||'',model:x.model||'',location:x.location||'',rental_status:x.rentalStatus||x.rental_status||'',borrower:x.borrower||'',borrow_date:x.borrowDate||x.borrow_date||'',expected_return_date:x.expectedReturn||x.expectedReturnDate||x.expected_return_date||'',overdue_days:x.overdueDays||x.overdue_days||0,action_required:x.actionRequired||x.action_required||'',ac_plug_sn:x.acPlugSn||x.ac_plug_sn||'',clamp_sn:x.clampSn||x.clamp_sn||''};});}
  function rentalRows(){var p=stockPayload()||{},rows=p.rentals||[];if(!rows.length){try{rows=(SD_RENTAL_WORKFLOW_V260.cards||[]);}catch(ignore){rows=[];}}return rows.map(function(x){return{
    rental_id:x.rentalId||x.rental_id||'',id_code:x.idCode||x.id_code||'',serial_number:x.sn||x.serialNumber||x.serial_number||'',brand:x.brand||'',model:x.model||'',location:x.location||'',rental_status:x.rentalStatus||x.rental_status||x.workflowStatus||'',borrower:x.borrower||'',borrow_date:x.borrowDate||x.borrow_date||'',expected_return_date:x.expectedReturn||x.expectedReturnDate||x.expected_return_date||x.dueDate||'',overdue_days:x.overdueDays||x.overdue_days||0,return_date:x.returnDate||x.return_date||'',action_required:x.actionRequired||x.action_required||x.borrowerAction||'',note:x.note||x.adminNote||''};});}
  function safeExport(fn){try{return fn();}catch(e){if(w.Swal)Swal.fire('Export Error',e.message||String(e),'error');return{success:false,message:e.message||String(e)};}}
  w.sd_exportSummary=function(){return exportChunkedSheets([{key:'summary',name:'Summary'}],'Infusion_Pump_Dashboard_Summary');};
  w.sd_exportContractSummaryExcel=w.sd_exportContracts=function(){return exportChunkedSheets([{key:'contract',name:'Infusion Rental History'}],'Infusion_Rental_History');};
  w.sd_exportEquipmentExcel=function(){return exportChunkedSheets([{key:'equipment',name:'Infusion Pump Dashboard'}],'Infusion_Pump_Equipment_List');};
  w.sc_exportCurrent=function(){return safeExport(function(){return exportRows(equipmentRows(),'Check_Stock_Equipment','Infusion Pump');});};
  function exportAccessories(){return safeExport(function(){var p=stockPayload()||{},rows=p.accessories||[];try{if(typeof SI!=='undefined'&&Array.isArray(SI.acc)&&SI.acc.length)rows=SI.acc;}catch(ignore){}return exportRows(rows.map(function(x){return{accessory_id:x.accessoryId||x.accessory_id||x.idCode||'',team:x.team||'',item_name:x.itemName||x.item_name||x.name||'',stock_qty:x.stockQty||x.stock_qty||x.qty||0,min_stock_qty:x.minStockQty||x.min_stock_qty||x.minStock||0,status:x.status||'',action_required:x.actionRequired||x.action_required||'',cost:x.cost||x.unitCost||x.unit_cost||x.totalCost||x.total_cost||0};}),'Accessories_Data','Accessories Data');});}
  var inventoryExportBase=w.si_exportCurrent;w.si_exportCurrent=function(){if(typeof SI!=='undefined'&&SI.tab!=='acc'&&typeof inventoryExportBase==='function')return inventoryExportBase();return exportAccessories();};w.si_exportAllSourceXlsxV3031=function(){return exportChunkedSheets([{key:'accessories_data',name:'Accessories Data'},{key:'accessories_dashboard',name:'Accessories Dashboard'}],'Inventory_Accessories');};

  var exportViewBase=w.CES_exportCurrentView;if(typeof exportViewBase==='function')w.CES_exportCurrentView=function(tab){tab=tab||((typeof w.CES_getCurrentTab==='function'&&w.CES_getCurrentTab())||w.CES_ACTIVE_TAB||'');if(tab==='check_stock')return w.sc_exportCurrent();return exportViewBase.apply(this,arguments);};

  w.sc_checkoutPrompt=function(id){if(!w.Swal)return;var today=new Date().toISOString().slice(0,10),html='<div class="ces-checkout-complete"><label>ผู้ยืม / Borrower *<input id="scCoBorrower" class="swal2-input"></label><label>Location *<input id="scCoLocation" class="swal2-input"></label><label>Borrow Date *<input id="scCoBorrow" class="swal2-input" type="date" value="'+today+'"></label><label>Due Date *<input id="scCoDue" class="swal2-input" type="date"></label><label class="wide">รายละเอียดสัญญาเช่า/ระยะ *<input id="scCoContract" class="swal2-input"></label><label>ผู้ประสานงาน *<input id="scCoCoord" class="swal2-input"></label><label>Email ผู้ประสานงาน *<input id="scCoEmail" class="swal2-input" type="email"></label><label>สัญญา CAL,PM<input id="scCoCal" class="swal2-input"></label><label>PLAN CAL,PM<input id="scCoPlanCal" class="swal2-input"></label><label>PLAN PM<input id="scCoPlanPm" class="swal2-input"></label><label>AC Plug SN<input id="scCoPlug" class="swal2-input"></label><label>Clamp SN<input id="scCoClamp" class="swal2-input"></label><label class="wide">หมายเหตุ<input id="scCoNote" class="swal2-input"></label></div>';
    Swal.fire({title:'Check-Out · '+esc(id),width:'min(820px,96vw)',html:html,showCancelButton:true,cancelButtonText:'ยกเลิก',confirmButtonText:'ยืนยัน',preConfirm:function(){function v(x){return String((d.getElementById(x)||{}).value||'').trim();}var p={borrower:v('scCoBorrower'),location:v('scCoLocation'),borrowDate:v('scCoBorrow'),expectedReturnDate:v('scCoDue'),contractDetail:v('scCoContract'),coordinator:v('scCoCoord'),coordinatorEmail:v('scCoEmail'),calPm:v('scCoCal'),planCalPm:v('scCoPlanCal'),planPm:v('scCoPlanPm'),acPlugSn:v('scCoPlug'),clampSn:v('scCoClamp'),note:v('scCoNote')};if(!p.borrower||!p.location||!p.borrowDate||!p.expectedReturnDate||!p.contractDetail||!p.coordinator||!p.coordinatorEmail){Swal.showValidationMessage('กรอกผู้ยืม, สถานที่, วันยืม, วันคืน, รายละเอียดสัญญา, ผู้ประสานงาน และ Email ให้ครบ');return false;}return p;}}).then(function(x){if(!x.isConfirmed)return;Swal.fire({title:'กำลัง Check-Out…',showConfirmButton:false,allowOutsideClick:false,didOpen:function(){Swal.showLoading();}});api('cesStock_checkout',[Object.assign({idCode:id,user:(w.CES_CURRENT_USER||{}).id||''},x.value)]).then(function(r){if(!r||r.success===false)throw new Error(r&&r.message||'Checkout failed');Swal.fire('สำเร็จ','เปลี่ยนสถานะเป็น เช่ายืม และบันทึกรายละเอียดแล้ว','success');if(typeof w.initStockCheckModule==='function')w.initStockCheckModule(true);}).catch(function(e){Swal.fire('Check-Out Error',e.message||String(e),'error');});});
  };

  w.loadNotificationLog=function(){var root=d.getElementById('nc-log');if(!root)return Promise.resolve();root.innerHTML='<div class="py-8 text-center"><i class="fas fa-circle-notch fa-spin text-blue-600"></i></div>';return api('getNotificationLog',[{limit:100}]).then(function(r){if(!r||r.success===false)throw new Error(r&&r.message||'Cannot load log');var rows=r.rows||[];root.innerHTML=rows.length?'<table><thead><tr>'+(r.headers||[]).map(function(h){return'<th>'+esc(h)+'</th>';}).join('')+'</tr></thead><tbody>'+rows.map(function(row){return'<tr>'+row.map(function(v,i){var cls=i===7?String(v).toLowerCase():'';return'<td class="'+cls+'">'+esc(v)+'</td>';}).join('')+'</tr>';}).join('')+'</tbody></table>':'<div class="py-8 text-center text-slate-400">No notification history yet.</div>';}).catch(function(e){root.innerHTML='<div class="py-8 text-center text-red-600">'+esc(e.message||e)+'</div>';});};
  var loadConfig=w.loadNotificationConfig;if(typeof loadConfig==='function')w.loadNotificationConfig=function(){var p=loadConfig.apply(this,arguments);Promise.resolve(p).finally(function(){w.loadNotificationLog();});return p;};

  w.CES_captureElementPdfExact=async function(target,fileName){
    var el=typeof target==='string'?d.querySelector(target):target;if(!el)throw new Error('PDF target not found.');
    if(!w.html2canvas||!(w.jspdf&&w.jspdf.jsPDF))throw new Error('PDF libraries are unavailable. Please refresh and try again.');
    var width=Math.max(1100,el.scrollWidth,el.getBoundingClientRect().width),host=d.createElement('div'),clone=el.cloneNode(true);
    host.setAttribute('aria-hidden','true');host.style.cssText='position:fixed;left:-30000px;top:0;width:'+width+'px;background:#fff;z-index:-1;pointer-events:none;';clone.style.width=width+'px';clone.style.maxWidth='none';clone.style.height='auto';clone.style.maxHeight='none';clone.style.overflow='visible';host.appendChild(clone);d.body.appendChild(host);
    try{
      var originals=el.querySelectorAll('input,textarea,select'),copies=clone.querySelectorAll('input,textarea,select');originals.forEach(function(x,i){var y=copies[i];if(!y)return;if(x.tagName==='SELECT')y.selectedIndex=x.selectedIndex;else{y.value=x.value;if(x.type==='checkbox'||x.type==='radio')y.checked=x.checked;}});
      var oldCanvas=el.querySelectorAll('canvas'),newCanvas=clone.querySelectorAll('canvas');oldCanvas.forEach(function(x,i){var y=newCanvas[i];if(!y)return;try{var img=d.createElement('img');img.src=x.toDataURL('image/png');img.style.cssText='display:block;width:'+Math.max(1,x.getBoundingClientRect().width)+'px;height:'+Math.max(1,x.getBoundingClientRect().height)+'px;';y.replaceWith(img);}catch(ignoreCanvas){}});
      clone.querySelectorAll('*').forEach(function(x){var cs=w.getComputedStyle(x);if(/auto|scroll|hidden/.test(cs.overflow+cs.overflowY)){x.style.overflow='visible';x.style.maxHeight='none';if(x.scrollHeight>x.clientHeight)x.style.height=x.scrollHeight+'px';}});
      if(d.fonts&&d.fonts.ready)await d.fonts.ready;await new Promise(function(resolve){requestAnimationFrame(function(){requestAnimationFrame(resolve);});});
      var canvas=await w.html2canvas(clone,{scale:2,useCORS:true,allowTaint:false,backgroundColor:'#ffffff',width:width,height:Math.max(clone.scrollHeight,clone.offsetHeight),windowWidth:width,windowHeight:Math.max(clone.scrollHeight,clone.offsetHeight),scrollX:0,scrollY:0,logging:false});
      var pdf=new w.jspdf.jsPDF({orientation:'landscape',unit:'mm',format:'a4',compress:true}),pw=297,ph=210,margin=6,imgW=pw-margin*2,pageH=ph-margin*2,pagePx=Math.max(1,Math.floor(canvas.width*pageH/imgW)),offset=0,page=0;
      while(offset<canvas.height){var sliceH=Math.min(pagePx,canvas.height-offset),part=d.createElement('canvas');part.width=canvas.width;part.height=sliceH;part.getContext('2d').drawImage(canvas,0,offset,canvas.width,sliceH,0,0,canvas.width,sliceH);if(page++)pdf.addPage('a4','landscape');pdf.addImage(part.toDataURL('image/jpeg',.94),'JPEG',margin,margin,imgW,sliceH*imgW/canvas.width,'','FAST');offset+=sliceH;}
      pdf.save((fileName||'CES_Hub')+'_'+new Date().toISOString().slice(0,10)+'.pdf');return{success:true,pages:page,width:canvas.width,height:canvas.height};
    }finally{host.remove();}
  };
  w.sd_printDashboard=function(){return w.CES_captureElementPdfExact('#view-stock_dashboard .stockpro-shell','Infusion_Pump_Dashboard');};w.si_printInventory=function(){return w.CES_captureElementPdfExact('#view-inventory .stockpro-shell','Inventory');};var mcpBase=w.mcpExportPdf;if(typeof mcpBase==='function')w.mcpExportPdf=function(){return w.CES_captureElementPdfExact('#view-master_cal_pm_plan','Master_CAL_PM_Plan').catch(function(){return mcpBase();});};var servicePdfBase=w.exportServiceToPDF,reportPdfBase=w.exportReportToPDF;if(typeof servicePdfBase==='function')w.exportServiceToPDF=function(){return w.CES_captureElementPdfExact('#view-service','Service_CSI').catch(function(){return servicePdfBase();});};if(typeof reportPdfBase==='function')w.exportReportToPDF=function(){return w.CES_captureElementPdfExact('#view-report','Report_CSI').catch(function(){return reportPdfBase();});};
})(window,document);
